"""Canonical Celery task names used across the runtimes."""

PURGE_OLD_TASK_EXECUTIONS_TASK = "maintenance.purge_old_task_executions"
PURGE_STALE_APPLICATIONS_TASK = "maintenance.purge_stale_applications"
PURGE_STALE_MACHINES_TASK = "maintenance.purge_stale_machines"
DISPATCH_ENABLED_PROVIDER_SYNCS_TASK = "providers.dispatch_enabled_syncs"
RUN_PROVIDER_TASK = "providers.run"
RUN_PROVIDER_MACHINE_TASK = "providers.run_machine"
RUN_PROVISIONER_TASK = "provisioners.run"
SYNC_APPLICATION_INVENTORY_DISCOVERY_TASK = "applications.sync_inventory_discovery"
DISPATCH_DUE_APPLICATION_METRICS_SYNCS_TASK = "applications.dispatch_due_metrics_syncs"
SYNC_APPLICATION_METRICS_TASK = "applications.sync_metrics"
DISPATCH_DUE_MACHINE_PROVISIONER_JOBS_TASK = "scheduler.dispatch_due_machine_provisioner_jobs"
