"""sync model constraints

Revision ID: 126a0810958b
Revises: 6f62a8e4b1c9
Create Date: 2026-05-13 16:16:24.345897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '126a0810958b'
down_revision: Union[str, Sequence[str], None] = '6f62a8e4b1c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name != 'sqlite':
        op.create_unique_constraint(
            'uq_machine_provider_provisioners_pair',
            'machine_provider_provisioners',
            ['provider_id', 'provisioner_id'],
        )
    op.drop_index(op.f('ix_machine_recommendations_acknowledged_at'), table_name='machine_recommendations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f('ix_machine_recommendations_acknowledged_at'),
        'machine_recommendations',
        ['acknowledged_at'],
        unique=False,
    )
    if op.get_bind().dialect.name != 'sqlite':
        op.drop_constraint(
            'uq_machine_provider_provisioners_pair',
            'machine_provider_provisioners',
            type_='unique',
        )
    # ### end Alembic commands ###
