"""initial schema

Revision ID: 1365251cef3b
Revises: 
Create Date: 2026-05-13 18:22:48.538311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from internal.infra.db.base import EncryptedJSONType
from internal.infra.db.base import JSONType

# revision identifiers, used by Alembic.
revision: str = '1365251cef3b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('environment', sa.String(length=128), nullable=False),
    sa.Column('region', sa.String(length=128), nullable=False),
    sa.Column('sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('name', 'environment', 'region', name='uq_applications_name_environment_region')
    )
    op.create_index(op.f('ix_applications_environment'), 'applications', ['environment'], unique=False)
    op.create_index(op.f('ix_applications_name'), 'applications', ['name'], unique=False)
    op.create_index(op.f('ix_applications_region'), 'applications', ['region'], unique=False)
    op.create_index(op.f('ix_applications_sync_at'), 'applications', ['sync_at'], unique=False)
    op.create_index(op.f('ix_applications_sync_scheduled_at'), 'applications', ['sync_scheduled_at'], unique=False)
    op.create_table('celery_task_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('result', JSONType, nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_celery_task_executions'))
    )
    op.create_index(op.f('ix_celery_task_executions_queued_at'), 'celery_task_executions', ['queued_at'], unique=False)
    op.create_index('ix_celery_task_executions_resource', 'celery_task_executions', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_celery_task_executions_resource_id'), 'celery_task_executions', ['resource_id'], unique=False)
    op.create_index(op.f('ix_celery_task_executions_resource_type'), 'celery_task_executions', ['resource_type'], unique=False)
    op.create_index(op.f('ix_celery_task_executions_status'), 'celery_task_executions', ['status'], unique=False)
    op.create_index(op.f('ix_celery_task_executions_task_id'), 'celery_task_executions', ['task_id'], unique=True)
    op.create_index(op.f('ix_celery_task_executions_task_name'), 'celery_task_executions', ['task_name'], unique=False)
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extra', JSONType, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platforms'))
    )
    op.create_index(op.f('ix_platforms_name'), 'platforms', ['name'], unique=True)
    op.create_table('machine_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('config', EncryptedJSONType(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], name=op.f('fk_machine_providers_platform_id_platforms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_machine_providers')),
    sa.UniqueConstraint('platform_id', 'name', name='uq_machine_providers_platform_name')
    )
    op.create_index(op.f('ix_machine_providers_scope'), 'machine_providers', ['scope'], unique=False)
    op.create_table('machine_provisioners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('config', EncryptedJSONType(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('cron', sa.String(length=64), nullable=False),
    sa.Column('last_scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], name=op.f('fk_machine_provisioners_platform_id_platforms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_machine_provisioners')),
    sa.UniqueConstraint('platform_id', 'name', name='uq_machine_provisioners_platform_name')
    )
    op.create_table('machine_provider_provisioners',
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('provisioner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['machine_providers.id'], name=op.f('fk_machine_provider_provisioners_provider_id_machine_providers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provisioner_id'], ['machine_provisioners.id'], name=op.f('fk_machine_provider_provisioners_provisioner_id_machine_provisioners'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('provider_id', 'provisioner_id', name=op.f('pk_machine_provider_provisioners')),
    sa.UniqueConstraint('provider_id', 'provisioner_id', name='uq_machine_provider_provisioners_pair')
    )
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('application', sa.String(length=255), nullable=True),
    sa.Column('source_provisioner_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('environment', sa.String(length=128), nullable=True),
    sa.Column('cpu', sa.Float(), nullable=True),
    sa.Column('ram_mb', sa.Float(), nullable=True),
    sa.Column('disk_mb', sa.Float(), nullable=True),
    sa.Column('extra', JSONType, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], name=op.f('fk_machines_platform_id_platforms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_provisioner_id'], ['machine_provisioners.id'], name=op.f('fk_machines_source_provisioner_id_machine_provisioners'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_machines')),
    sa.UniqueConstraint('platform_id', 'hostname', name='uq_machines_platform_hostname'),
    sa.UniqueConstraint('source_provisioner_id', 'external_id', name='uq_machines_provisioner_external_id')
    )
    op.create_index(op.f('ix_machines_application'), 'machines', ['application'], unique=False)
    op.create_index(op.f('ix_machines_environment'), 'machines', ['environment'], unique=False)
    op.create_index(op.f('ix_machines_external_id'), 'machines', ['external_id'], unique=False)
    op.create_index(op.f('ix_machines_hostname'), 'machines', ['hostname'], unique=False)
    op.create_index(op.f('ix_machines_region'), 'machines', ['region'], unique=False)
    op.create_table('machine_cpu_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], name=op.f('fk_machine_cpu_metrics_machine_id_machines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['machine_providers.id'], name=op.f('fk_machine_cpu_metrics_provider_id_machine_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_machine_cpu_metrics')),
    sa.UniqueConstraint('provider_id', 'machine_id', 'date', name='uq_machine_cpu_metrics_day')
    )
    op.create_index(op.f('ix_machine_cpu_metrics_date'), 'machine_cpu_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_machine_cpu_metrics_machine_id'), 'machine_cpu_metrics', ['machine_id'], unique=False)
    op.create_index('ix_machine_cpu_metrics_provider_date', 'machine_cpu_metrics', ['provider_id', 'date'], unique=False)
    op.create_table('machine_disk_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], name=op.f('fk_machine_disk_metrics_machine_id_machines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['machine_providers.id'], name=op.f('fk_machine_disk_metrics_provider_id_machine_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_machine_disk_metrics')),
    sa.UniqueConstraint('provider_id', 'machine_id', 'date', name='uq_machine_disk_metrics_day')
    )
    op.create_index(op.f('ix_machine_disk_metrics_date'), 'machine_disk_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_machine_disk_metrics_machine_id'), 'machine_disk_metrics', ['machine_id'], unique=False)
    op.create_index('ix_machine_disk_metrics_provider_date', 'machine_disk_metrics', ['provider_id', 'date'], unique=False)
    op.create_table('machine_flavor_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('source_provisioner_id', sa.Integer(), nullable=True),
    sa.Column('cpu', sa.Float(), nullable=True),
    sa.Column('ram_mb', sa.Float(), nullable=True),
    sa.Column('disk_mb', sa.Float(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], name=op.f('fk_machine_flavor_history_machine_id_machines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_provisioner_id'], ['machine_provisioners.id'], name=op.f('fk_machine_flavor_history_source_provisioner_id_machine_provisioners'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_machine_flavor_history'))
    )
    op.create_index(op.f('ix_machine_flavor_history_changed_at'), 'machine_flavor_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_machine_flavor_history_machine_id'), 'machine_flavor_history', ['machine_id'], unique=False)
    op.create_table('machine_optimizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('current_machine_id', sa.Integer(), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('window_size', sa.Integer(), nullable=False),
    sa.Column('min_cpu', sa.Integer(), nullable=False),
    sa.Column('max_cpu', sa.Integer(), nullable=False),
    sa.Column('min_ram_mb', sa.Integer(), nullable=False),
    sa.Column('max_ram_mb', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=255), nullable=True),
    sa.Column('current_cpu', sa.Float(), nullable=True),
    sa.Column('current_ram_mb', sa.Float(), nullable=True),
    sa.Column('current_disk_mb', sa.Float(), nullable=True),
    sa.Column('target_cpu', sa.Float(), nullable=True),
    sa.Column('target_ram_mb', sa.Float(), nullable=True),
    sa.Column('target_disk_mb', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(is_current AND current_machine_id IS NOT NULL AND superseded_at IS NULL) OR ((NOT is_current) AND current_machine_id IS NULL AND superseded_at IS NOT NULL)', name=op.f('ck_machine_optimizations_ck_machine_optimizations_current_state')),
    sa.CheckConstraint('current_machine_id IS NULL OR current_machine_id = machine_id', name=op.f('ck_machine_optimizations_ck_machine_optimizations_current_machine_matches_machine')),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], name=op.f('fk_machine_optimizations_machine_id_machines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_machine_optimizations')),
    sa.UniqueConstraint('current_machine_id', name='uq_machine_optimizations_current_machine_id'),
    sa.UniqueConstraint('machine_id', 'revision', name='uq_machine_optimizations_machine_revision')
    )
    op.create_index('ix_machine_optimizations_machine_current', 'machine_optimizations', ['machine_id', 'is_current'], unique=False)
    op.create_index(op.f('ix_machine_optimizations_machine_id'), 'machine_optimizations', ['machine_id'], unique=False)
    op.create_index('ix_machine_optimizations_superseded_at', 'machine_optimizations', ['superseded_at'], unique=False)
    op.create_table('machine_ram_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], name=op.f('fk_machine_ram_metrics_machine_id_machines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['machine_providers.id'], name=op.f('fk_machine_ram_metrics_provider_id_machine_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_machine_ram_metrics')),
    sa.UniqueConstraint('provider_id', 'machine_id', 'date', name='uq_machine_ram_metrics_day')
    )
    op.create_index(op.f('ix_machine_ram_metrics_date'), 'machine_ram_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_machine_ram_metrics_machine_id'), 'machine_ram_metrics', ['machine_id'], unique=False)
    op.create_index('ix_machine_ram_metrics_provider_date', 'machine_ram_metrics', ['provider_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_machine_ram_metrics_provider_date', table_name='machine_ram_metrics')
    op.drop_index(op.f('ix_machine_ram_metrics_machine_id'), table_name='machine_ram_metrics')
    op.drop_index(op.f('ix_machine_ram_metrics_date'), table_name='machine_ram_metrics')
    op.drop_table('machine_ram_metrics')
    op.drop_index('ix_machine_optimizations_superseded_at', table_name='machine_optimizations')
    op.drop_index(op.f('ix_machine_optimizations_machine_id'), table_name='machine_optimizations')
    op.drop_index('ix_machine_optimizations_machine_current', table_name='machine_optimizations')
    op.drop_table('machine_optimizations')
    op.drop_index(op.f('ix_machine_flavor_history_machine_id'), table_name='machine_flavor_history')
    op.drop_index(op.f('ix_machine_flavor_history_changed_at'), table_name='machine_flavor_history')
    op.drop_table('machine_flavor_history')
    op.drop_index('ix_machine_disk_metrics_provider_date', table_name='machine_disk_metrics')
    op.drop_index(op.f('ix_machine_disk_metrics_machine_id'), table_name='machine_disk_metrics')
    op.drop_index(op.f('ix_machine_disk_metrics_date'), table_name='machine_disk_metrics')
    op.drop_table('machine_disk_metrics')
    op.drop_index('ix_machine_cpu_metrics_provider_date', table_name='machine_cpu_metrics')
    op.drop_index(op.f('ix_machine_cpu_metrics_machine_id'), table_name='machine_cpu_metrics')
    op.drop_index(op.f('ix_machine_cpu_metrics_date'), table_name='machine_cpu_metrics')
    op.drop_table('machine_cpu_metrics')
    op.drop_index(op.f('ix_machines_region'), table_name='machines')
    op.drop_index(op.f('ix_machines_hostname'), table_name='machines')
    op.drop_index(op.f('ix_machines_external_id'), table_name='machines')
    op.drop_index(op.f('ix_machines_environment'), table_name='machines')
    op.drop_index(op.f('ix_machines_application'), table_name='machines')
    op.drop_table('machines')
    op.drop_table('machine_provider_provisioners')
    op.drop_table('machine_provisioners')
    op.drop_index(op.f('ix_machine_providers_scope'), table_name='machine_providers')
    op.drop_table('machine_providers')
    op.drop_index(op.f('ix_platforms_name'), table_name='platforms')
    op.drop_table('platforms')
    op.drop_index(op.f('ix_celery_task_executions_task_name'), table_name='celery_task_executions')
    op.drop_index(op.f('ix_celery_task_executions_task_id'), table_name='celery_task_executions')
    op.drop_index(op.f('ix_celery_task_executions_status'), table_name='celery_task_executions')
    op.drop_index(op.f('ix_celery_task_executions_resource_type'), table_name='celery_task_executions')
    op.drop_index(op.f('ix_celery_task_executions_resource_id'), table_name='celery_task_executions')
    op.drop_index('ix_celery_task_executions_resource', table_name='celery_task_executions')
    op.drop_index(op.f('ix_celery_task_executions_queued_at'), table_name='celery_task_executions')
    op.drop_table('celery_task_executions')
    op.drop_index(op.f('ix_applications_sync_scheduled_at'), table_name='applications')
    op.drop_index(op.f('ix_applications_sync_at'), table_name='applications')
    op.drop_index(op.f('ix_applications_region'), table_name='applications')
    op.drop_index(op.f('ix_applications_name'), table_name='applications')
    op.drop_index(op.f('ix_applications_environment'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
