"""add machine recommendations

Revision ID: db0aaeafbd5c
Revises: 755ada20c181
Create Date: 2026-05-08 18:14:06.947722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db0aaeafbd5c'
down_revision: Union[str, Sequence[str], None] = '755ada20c181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('current_machine_id', sa.Integer(), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('window_size', sa.Integer(), nullable=False),
    sa.Column('min_cpu', sa.Integer(), nullable=False),
    sa.Column('max_cpu', sa.Integer(), nullable=False),
    sa.Column('min_ram_mb', sa.Integer(), nullable=False),
    sa.Column('max_ram_mb', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_cpu', sa.Float(), nullable=True),
    sa.Column('current_ram_mb', sa.Float(), nullable=True),
    sa.Column('current_disk_mb', sa.Float(), nullable=True),
    sa.Column('target_cpu', sa.Float(), nullable=True),
    sa.Column('target_ram_mb', sa.Float(), nullable=True),
    sa.Column('target_disk_mb', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(is_current AND current_machine_id IS NOT NULL AND superseded_at IS NULL) OR ((NOT is_current) AND current_machine_id IS NULL AND superseded_at IS NOT NULL)', name=op.f('ck_machine_recommendations_ck_machine_recommendations_current_state')),
    sa.CheckConstraint('current_machine_id IS NULL OR current_machine_id = machine_id', name=op.f('ck_machine_recommendations_ck_machine_recommendations_current_machine_matches_machine')),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], name=op.f('fk_machine_recommendations_machine_id_machines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_machine_recommendations')),
    sa.UniqueConstraint('current_machine_id', name='uq_machine_recommendations_current_machine_id'),
    sa.UniqueConstraint('machine_id', 'revision', name='uq_machine_recommendations_machine_revision')
    )
    op.create_index('ix_machine_recommendations_machine_current', 'machine_recommendations', ['machine_id', 'is_current'], unique=False)
    op.create_index(op.f('ix_machine_recommendations_machine_id'), 'machine_recommendations', ['machine_id'], unique=False)
    op.create_index('ix_machine_recommendations_superseded_at', 'machine_recommendations', ['superseded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_machine_recommendations_superseded_at', table_name='machine_recommendations')
    op.drop_index(op.f('ix_machine_recommendations_machine_id'), table_name='machine_recommendations')
    op.drop_index('ix_machine_recommendations_machine_current', table_name='machine_recommendations')
    op.drop_table('machine_recommendations')
    # ### end Alembic commands ###
